In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
#sentrences

In [3]:
sent = ["the glass of milk",
       "the glass of juice",
       "i am a good boy",
       "I am a good developer",
       "understand the meaning of word",
       "your videos are good"]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'i am a good boy',
 'I am a good developer',
 'understand the meaning of word',
 'your videos are good']

In [5]:
voc_size = 10000

#### One hot representation

In [9]:
onehot = [one_hot(words, voc_size)for words in sent]

In [10]:
print(onehot)

[[3340, 3784, 6594, 6495], [3340, 3784, 6594, 6474], [5081, 8996, 2219, 1204, 3877], [5081, 8996, 2219, 1204, 1855], [8446, 3340, 3766, 6594, 1207], [4013, 6820, 7307, 1204]]


#### word embedding Representation

In [11]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [12]:
import numpy as np

In [13]:
sent_lenth = 8
embeded_doc = pad_sequences(onehot, padding = 'pre', maxlen=sent_lenth)
print(embeded_doc)

[[   0    0    0    0 3340 3784 6594 6495]
 [   0    0    0    0 3340 3784 6594 6474]
 [   0    0    0 5081 8996 2219 1204 3877]
 [   0    0    0 5081 8996 2219 1204 1855]
 [   0    0    0 8446 3340 3766 6594 1207]
 [   0    0    0    0 4013 6820 7307 1204]]


In [14]:
dim=10

In [20]:
#adding embedding layer to take featurized representation

In [15]:
model = Sequential()
model.add(Embedding(voc_size, 10, input_length= sent_lenth))
model.compile('adam', 'mse')

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [17]:
print(model.predict(embeded_doc))

[[[ 1.06414668e-02 -4.81299050e-02  2.42554583e-02  4.37540077e-02
    3.63241881e-04  3.45125049e-03  2.97696851e-02 -4.35988307e-02
    4.77891080e-02  1.82193033e-02]
  [ 1.06414668e-02 -4.81299050e-02  2.42554583e-02  4.37540077e-02
    3.63241881e-04  3.45125049e-03  2.97696851e-02 -4.35988307e-02
    4.77891080e-02  1.82193033e-02]
  [ 1.06414668e-02 -4.81299050e-02  2.42554583e-02  4.37540077e-02
    3.63241881e-04  3.45125049e-03  2.97696851e-02 -4.35988307e-02
    4.77891080e-02  1.82193033e-02]
  [ 1.06414668e-02 -4.81299050e-02  2.42554583e-02  4.37540077e-02
    3.63241881e-04  3.45125049e-03  2.97696851e-02 -4.35988307e-02
    4.77891080e-02  1.82193033e-02]
  [-1.48027316e-02  3.19412015e-02  1.25262775e-02  4.52008136e-02
   -3.63840945e-02 -2.51898300e-02 -3.12376264e-02 -4.26381342e-02
    3.71177904e-02 -1.06080547e-02]
  [-1.56966336e-02 -3.13371047e-02 -2.79034134e-02 -2.31748223e-02
   -1.45880468e-02 -2.16401741e-03  3.23466770e-02 -3.17254439e-02
    1.43312477e-

In [18]:
embeded_doc[0]

array([   0,    0,    0,    0, 3340, 3784, 6594, 6495])

In [21]:
# 0 got conveted into ten dimension vectors as 0.01064147

In [22]:
print(model.predict(embeded_doc[0]))

[[[ 0.01064147 -0.04812991  0.02425546  0.04375401  0.00036324
    0.00345125  0.02976969 -0.04359883  0.04778911  0.0182193 ]]

 [[ 0.01064147 -0.04812991  0.02425546  0.04375401  0.00036324
    0.00345125  0.02976969 -0.04359883  0.04778911  0.0182193 ]]

 [[ 0.01064147 -0.04812991  0.02425546  0.04375401  0.00036324
    0.00345125  0.02976969 -0.04359883  0.04778911  0.0182193 ]]

 [[ 0.01064147 -0.04812991  0.02425546  0.04375401  0.00036324
    0.00345125  0.02976969 -0.04359883  0.04778911  0.0182193 ]]

 [[-0.01480273  0.0319412   0.01252628  0.04520081 -0.03638409
   -0.02518983 -0.03123763 -0.04263813  0.03711779 -0.01060805]]

 [[-0.01569663 -0.0313371  -0.02790341 -0.02317482 -0.01458805
   -0.00216402  0.03234668 -0.03172544  0.01433125 -0.02295893]]

 [[-0.04572424 -0.04301431  0.01134765  0.03860283 -0.03432051
    0.03453526  0.0159854  -0.02944666 -0.03169121  0.01504968]]

 [[-0.00335731  0.01439727  0.00339208 -0.01258457 -0.01781875
   -0.01343384 -0.00357248  0.0070